#!/usr/bin/env python

import os
import sys
import torque
import slurm
import nodeview

def _which(program):

    fpath, fname = os.path.split(program)
    if fpath:
        if os.path.isfile(program) and os.access(program, os.X_OK):
            return program
    else:
        for path in os.environ["PATH"].split(os.pathsep):
            path = path.strip('"')
            exe_file = os.path.join(path, program)
            if os.path.isfile(exe_file) and os.access(exe_file, os.X_OK):
                return exe_file

    return None

if __name__ == '__main__':
    if _which('qsub') is not None:
        for node in torque.generate_nodelist( ):
            nodeview.print_node_line( node )
    elif _which('sinfo') is not None:
        for node in slurm.generate_nodelist( ):
            nodeview.print_node_line( node )
    else:
        sys.stderr.write('no supported resource manager detected\n')
        sys.exit(1)
